import Head from "next/head";
import Banner from "./components/Banner";
import Header from "./components/Header";
import ProductFeeds from "./components/ProductFeed";

export default function Home({ products }) {
  console.log(products);
  return (
    <div className=" bg-gray-100">
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header component */}
      <Header />

      {/* main container */}
      <main className=" max-w-screen-2xl mx-auto">
        {/* banner */}

        <Banner />

        {/* product feed */}
        <ProductFeeds products={products} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  return {
    props: { products }, // will be passed to the page component as props
  };
}
